#!/usr/bin/env bash

if [ -n "${__ssh_dynconf_included__}" ]; then return 0; fi

export __ssh_dynconf_included__=true

# =============================== > Settings < =============================== #

if [ -z "${SSH_DYNCONF_DIR}" ]; then
    if [ -n "$BASH_VERSION" ]; then
        current_file="${BASH_SOURCE[0]}"
    elif [ -n "$ZSH_VERSION" ]; then
        current_file="${(%):-%N}"
    fi
    SSH_DYNCONF_DIR="$(dirname $(readlink -f "${current_file}"))"
fi

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================== > Source submodules < =========================== #
source ${SSH_DYNCONF_DIR}/submodules/bash-aux/bash-aux-init
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============================= > Source files < ============================= #
source ${SSH_DYNCONF_DIR}/functions/ssh_available_hosts
source ${SSH_DYNCONF_DIR}/functions/ssh_host_available
source ${SSH_DYNCONF_DIR}/functions/ssh_host_name
source ${SSH_DYNCONF_DIR}/functions/ssh_config_update
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================= > Export all functions < ========================= #
eval "$(declare -F |
    perl -p0e "s/declare\s+-f\s+(.*)\s*$/export -f \${1}/gmi" )"
# ────────────────────────────────── <end> ─────────────────────────────────── #

x