#!/usr/bin/env bash

if [ -n "${__ssh_find_host__}" ]; then return 0; fi

export __ssh_find_host__=true

# =============================== > Settings < =============================== #

if [ -z "${SSH_FIND_HOST_DIR}" ]; then
    SSH_FIND_HOST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================== > Source submodules < =========================== #
cd $SSH_FIND_HOST_DIR/submodules/bash-doc && 
    source ${SSH_FIND_HOST_DIR}/submodules/bash-doc/bash-doc-init
cd $SSH_FIND_HOST_DIR/
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============================= > Source files < ============================= #
cd ${SSH_FIND_HOST_DIR}/functions
source ./normalize_path
source ./read_non_blocking
source ./ssh_available_hosts
source ./ssh_host_available
source ./ssh_host_name
source ./ssh_config_update
cd ${SSH_FIND_HOST_DIR}/
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ========================= > Export all functions < ========================= #
eval "$(declare -F | sed -e 's/-f /-fx /')"
# ────────────────────────────────── <end> ─────────────────────────────────── #
